services:
  postgres:
    image: pgvector/pgvector:pg17
    restart: always
    environment:
      POSTGRES_USER: ${PG_LOCAL_USER}
      POSTGRES_PASSWORD: ${PG_LOCAL_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${PG_PORT}:5432

  ollama:
    image: ollama/ollama
    restart: always
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - ${OL_PORT}:11434

volumes:
  pgdata:
  ollama_data:
